# Generated by Django 5.2.3 on 2025-06-23 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('checking_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('savings_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('business_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('crypto_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
